// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pk_loan_crud.Data;

#nullable disable

namespace pk_loan_crud.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("pk_loan_crud.Data.PKLoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15, 4)")
                        .HasColumnName("Amount");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("Bank_Code");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("Company");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("Currency_code");

                    b.Property<string>("CvCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("CV_Code");

                    b.Property<decimal>("FrAmount")
                        .HasColumnType("decimal(15, 4)")
                        .HasColumnName("Fr_amount");

                    b.Property<decimal>("FrInterestAmt")
                        .HasColumnType("decimal(15, 4)")
                        .HasColumnName("Fr_interest_amt");

                    b.Property<decimal>("InterestAmt")
                        .HasColumnType("decimal(15, 4)")
                        .HasColumnName("Interest_amt");

                    b.Property<int>("LoanType")
                        .HasColumnType("integer")
                        .HasColumnName("Loan_Type");

                    b.Property<int>("MonthNo")
                        .HasColumnType("integer")
                        .HasColumnName("Month_No");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(15, 4)")
                        .HasColumnName("Rate");

                    b.Property<int>("YearNo")
                        .HasColumnType("integer")
                        .HasColumnName("Year_No");

                    b.HasKey("Id");

                    b.ToTable("PK_LOAN");
                });
#pragma warning restore 612, 618
        }
    }
}
